### ISSUE TITLE
Connection close

### ISSUE THREAD

**Issue by vit1251** [mosquito/aiormq#109]
How to handle next error message:

```
DEBUG:aiormq.connection:Can not read bytes from server:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiormq/connection.py", line 381, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/usr/local/lib/python3.7/dist-packages/aiormq/connection.py", line 333, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
```

**Comment by mosquito** [comment]
This means that the server closed the connection when the background task tried to get the frame header. You should not react to this, but I don't want to hide this cause it's shows the server disconnection.

**Comment by vit1251** [comment]
@mosquito oh. There some misunderstanding. How I can register callback to make re-connect routine for example? Right not I see that is_close property is exists but it require make another one watchdog task.
