### ISSUE TITLE
Incomplete read error when closing connection

### ISSUE THREAD

**Issue by thmzlt** [mosquito/aiormq#32]
I'm getting the following traceback when stopping my connection:

```
Traceback (most recent call last):
  File "/nix/store/p8j6zgmwlr25cf4viyyqfalfnd9dh9y1-python3-3.7.2-env/lib/python3.7/site-packages/aiormq/connection.py", line 334, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/nix/store/p8j6zgmwlr25cf4viyyqfalfnd9dh9y1-python3-3.7.2-env/lib/python3.7/site-packages/aiormq/base.py", line 171, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/nix/store/p8j6zgmwlr25cf4viyyqfalfnd9dh9y1-python3-3.7.2-env/lib/python3.7/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/nix/store/p8j6zgmwlr25cf4viyyqfalfnd9dh9y1-python3-3.7.2-env/lib/python3.7/site-packages/aiormq/connection.py", line 285, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/nix/store/p8j6zgmwlr25cf4viyyqfalfnd9dh9y1-python3-3.7.2-env/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
```

I'm pretty much calling `channel.close()` and then `connection.close()` before stopping and closing the loop. Shouldn't it close without an error?

**Comment by thmzlt** [comment]
That is aiormq 2.4 but I get the same traceback on 2.5.

**Comment by decaz** [comment]
@thmzlt it should close without error, check it with the latest `2.7.5` version please.

**Comment by mosquito** [comment]
Yes! It's normal in case TCP connection problems. This exception means unexpected connection close while reading frame header.

**Comment by decaz** [comment]
Thanks. I guess it can be closed.

**Comment by talwrii** [comment]
So calling connection.close() will produce error messages on `DEBUG` when nothing unexpected has happened.

Here is a repro that causes this error message.

```
# repro.py
import asyncio
import aio_pika

import logging

logging.basicConfig(level=logging.DEBUG)


async def repro():
    while True:
        try:
            connection = await aio_pika.connect("amqp://guest:guest@rabbitmq/")
        except Exception:
            await asyncio.sleep(1)
        else:
            break

    channel = await connection.channel()
    queue = await channel.declare_queue("queue")
    await queue.consume(lambda *_: None)
    await channel.default_exchange.publish(
        aio_pika.Message(body="hello".encode("utf8")), routing_key="queue"
    )
    await connection.close()


asyncio.get_event_loop().run_until_complete(repro())
```

Dockerfile
```
FROM python

RUN pip3 install aio-pika
```

docker-compose.yml
```
version: '3.6'
services:
  rabbitmq:
    image: "rabbitmq"
  repro:
    build: .
    command: "python3 /app/repro.py"
    volumes:
      - ".:/app"

networks:
  default:
    name: rabbit
```

**Comment by talwrii** [comment]
Here is a branch that fixes all these warnings.

**Comment by sepetnit** [comment]
@talwrii, did you intent to create a branch that fixes this? I also see these warnings in my code and wondering if the correct solution is to avoid them instead of ignoring them.

**Comment by talwrii** [comment]
Whoops. Yep, think I got distracted here's a pull request: https://github.com/mosquito/aiormq/pull/86

**Comment by TBBle** [comment]
With aiormq 3.3.1 (on Python 3.8, in case it matters) this problem gets worse, because the `IncompleteReadError` gets turned into an `IncompatibleProtocolError` if it happens while connecting, which means you get an `IncompatibleProtocolError` with args, but the format string doesn't have args, so this code in exceptions.py
```
class AMQPError(Exception):
    reason = "An unspecified AMQP error has occurred: %s"

    def __repr__(self):
        return "<%s: %s>" % (self.__class__.__name__, self.reason % self.args)

class IncompatibleProtocolError(AMQPConnectionError):
    reason = "The protocol returned by the server is not supported"
```
causes this failure during shutdown:
```
2021-03-19 13:16:51,415 ERROR   asyncio] Exception in default exception handler
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1733, in call_exception_handler
    self.default_exception_handler(context)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1704, in default_exception_handler
    value = repr(value)
  File "C:\Program Files\Python38\lib\asyncio\base_tasks.py", line 9, in _task_repr_info
    info = base_futures._future_repr_info(task)
  File "C:\Program Files\Python38\lib\asyncio\base_futures.py", line 61, in _future_repr_info
    info.append(f'exception={future._exception!r}')
  File "C:\Users\paulh\AppData\Local\pypoetry\Cache\virtualenvs\webservice-YcZ_CzdI-py3.8\lib\site-packages\aiormq\exceptions.py", line 12, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self.reason % self.args)
TypeError: not all arguments converted during string formatting
```
as `self.args` was `('0 bytes read on a total of 1 expected bytes',)`, i.e. the `self.args` from `IncompleteReadError`.

I think this is because some intermediate point turned `IncompleteReadError` into `EOFError` but didn't strip the args.
