### ISSUE TITLE
Repeated TypeError in exceptions.py while attempting to cancel event loop tasks

### ISSUE THREAD

**Issue by gregdan3** [mosquito/aiormq#39]
```[2019-06-03 16:26:56,499] [        base_events.py:1640] [   ERROR]   Exception in default exception handler
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1634, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1605, in default_exception_handler
    value = repr(value)
  File "/usr/lib/python3.7/asyncio/base_tasks.py", line 9, in _task_repr_info
    info = base_futures._future_repr_info(task)
  File "/usr/lib/python3.7/asyncio/base_futures.py", line 60, in _future_repr_info
    info.append(f'exception={future._exception!r}')
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/exceptions.py", line 6, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self.message % self.args)
TypeError: not all arguments converted during string formatting
```
If I attempt to cancel the publish tasks after they have begun, this occurs inconsistently.
I have yet to find a specific cause of the issue.
This occurs in aio_pika 5.5.3 and aiormq 2.5.3

```
[2019-06-03 16:57:04,123] [         connection.py:380 ] [   DEBUG]   Reader task cancelled:
Traceback (most recent call last):
  File "./scrape.py", line 312, in main
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/channel.py", line 245, in _reader
    await self._on_deliver(frame)
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/channel.py", line 146, in _on_deliver
    header = await self._get_frame()    # type: ContentHeader
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/channel.py", line 79, in _get_frame
    self.frames.task_done()
  File "/usr/lib/python3.7/asyncio/queues.py", line 205, in task_done
    self._finished.set()
  File "/usr/lib/python3.7/asyncio/locks.py", line 270, in set
    for fut in self._waiters:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/connection.py", line 349, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/base.py", line 171, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/gregdan3/.local/lib/python3.7/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
concurrent.futures._base.CancelledError
```
This is the process that normally occurs, but again, this does not always occur as intended.

```
asyncio.ensure_future(publisher.run(), loop=loop)
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        _log.info("Shutting down Asyncio loop")
        all_tasks = asyncio.Task.all_tasks(loop=loop)
        for task in all_tasks:
            task.cancel()
        kill_task = asyncio.ensure_future(publisher.stop(), loop=loop)
        loop.run_until_complete(kill_task)
    finally:
        loop.close()
```
This is the specific code where I kill the tasks on the event loop.

**Comment by theSage21** [comment]
I'm seeing this exact error. I'm using aiohttp + aio_pika to consume things from rabbit and forward via a websocket.
