### ISSUE TITLE
 how to set a timeout param when connection is creating

### ISSUE THREAD

**Issue by xiaoliuhust** [mosquito/aiormq#64]
hi，
I have a question how to set a timeout param when connection is creating ,otherwise it takes about two heartbeat_interval(130s) to report ConnectionError: [Errno 110].I read aiormq's connection.py source code but still cannot find a way.
```
2019-11-08 15:12:27,242 consumer INFO /root/workspace/rabbitmq_connector.py start connect_to_rabbitmq
INFO:consumer:start connect to rabbitmq
Traceback (most recent call last):
  File "/root/workspace/python3.6/site-packages/aiormq/connection.py", line 227, in connect
    loop=self.loop
  File "/usr/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 110] Connect call failed ('192.168.20.251', 5672)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/workspace/python3.6/site-packagesrabbitmq_connector.py", line 140, in get_connection
    self.connection = await aiormq.connect(url)
  File "/root/workspace/python3.6/site-packages/aiormq/connection.py", line 521, in connect
    await connection.connect(client_properties or {})
  File "/root/workspace/python3.6/site-packages/aiormq/base.py", line 171, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/root/workspace/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/root/workspace/python3.6/site-packages/aiormq/connection.py", line 230, in connect
    raise ConnectionError(*e.args) from e
ConnectionError: [Errno 110] Connect call failed ('192.168.20.251', 5672)
2019-11-08 15:14:37,132 5f18209e-fac5-11e9-a5f4-000c293c5e0b consumer INFO /root/workspace/rabbitmq_connector.py get_connection 149 : connect rabbitmq failed:[Errno 110] Connect call failed ('192.168.20.251', 5672)
INFO:consumer:connect rabbitmq failed:[Errno 110] Connect call failed ('192.168.20.251', 5672)
```

**Comment by mosquito** [comment]
Better way to set timeout externally it’s using`asyncio.wait_for` I guess.

**Comment by xiaoliuhust** [comment]
I have tested that asyncio.wait_for is a good way, thanks for reply
