### ISSUE TITLE
ChannelInvalidStateError

### ISSUE THREAD

**Issue by levsh** [mosquito/aiormq#96]
Hi!
I have a questions. Is this a right behaviour that channel has an invalid state after attempt to consume from non existent queue?
Test case
```python
    async def test_channel(self, rabbitmq):
        connection = await aiormq.connect(config.backends["rabbitmq"].url)
        channel = await connection.channel()
        await channel.queue_declare("default", durable=True)

        def on_message(msg):
            print(msg)

        try:
            await channel.basic_consume("non_existent_queue", on_message)
        except Exception:
            LOG.exception("#1")

        try:
            await channel.basic_consume("default", on_message)
        except Exception:
            LOG.exception("#2")
```
output
```
2020-11-07 08:03:55,679 |ERROR| #1
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vagrant/dev/.../tests/tests_medium.py", line 142, in test_channel
    await channel.basic_consume("non_existent_queue", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no queue 'non_existent_queue' in vhost '/'
2020-11-07 08:03:55,686 |ERROR| #2
Traceback (most recent call last):
  File "/vagrant/dev/.../tests/tests_medium.py", line 147, in test_channel
    await channel.basic_consume("default", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 121, in rpc
    raise ChannelInvalidStateError("writer is None")
aiormq.exceptions.ChannelInvalidStateError: writer is None
```

The second case. Connection lost. Behaviour(exception type) depends on timeout.

```python
    async def test_lost_connection(self, rabbitmq):
        connection = await aiormq.connect(config.backends["rabbitmq"].url)
        channel = await connection.channel()
        await channel.queue_declare("default", durable=True)

        def on_message(msg):
            print(msg)

        await channel.basic_consume("default", on_message)

        rabbitmq.stop()

        # await asyncio.sleep(5)

        try:
            await channel.basic_consume("other", on_message)
        except Exception:
            LOG.exception("#1")
```
Output
```
Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<FutureStore.reject_all() done, defined at /home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py:65> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fc613b96280>()]>>
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_wrap_awaitable() done, defined at /home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py:685> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/vagrant/dev/.../tests/tests_medium.py", line 148, in test_lost_connection
    await channel.basic_consume("other", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 423, in __close_writer
    await writer.wait_closed()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 375, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<_wrap_awaitable() done, defined at /home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py:685> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/vagrant/dev/.../tests/tests_medium.py", line 148, in test_lost_connection
    await channel.basic_consume("other", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 423, in __close_writer
    await writer.wait_closed()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 375, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<_wrap_awaitable() done, defined at /home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py:685> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/vagrant/dev/.../tests/tests_medium.py", line 148, in test_lost_connection
    await channel.basic_consume("other", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 423, in __close_writer
    await writer.wait_closed()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 375, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.__reader() done, defined at /home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py:165> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/vagrant/dev/.../tests/tests_medium.py", line 148, in test_lost_connection
    await channel.basic_consume("other", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 423, in __close_writer
    await writer.wait_closed()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 375, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

after uncomment   `await asyncio.sleep(5)` get

```
2020-11-07 08:23:51,085 |ERROR| #1
Traceback (most recent call last):
  File "/vagrant/dev/.../tests/tests_medium.py", line 148, in test_lost_connection
    await channel.basic_consume("other", on_message)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 422, in basic_consume
    return await self.rpc(
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiormq/channel.py", line 121, in rpc
    raise ChannelInvalidStateError("writer is None")
aiormq.exceptions.ChannelInvalidStateError: writer is None
```

aiormq  3.3.1
Python 3.8.6

Thank you for help!

**Comment by nhumrich** [comment]
I also have this same issue

aiormq 3.3.1
Python 3.9.5

**Comment by mosquito** [comment]
Rabbitmq operates channels within a single connection. If the user performed an action with failure the channel is closing. If user continue to send frames to a closed channel, the broker will terminate the connection with an error.

aio-pika protects the connection and throws this exception when channel could not be used anymore. It's preferred because protects other opened channels.
